#%RAML 1.0
baseUri: https://qax.anypoint.mulesoft.com/mocking/api/v1/links/6c4d8241-aa20-4e8f-b2bd-bfed8bfa86ca/ # 
title: Mytest
documentation:
  - title: Simple Doc
    content: Simple Raml file to test git integration with.